[error] java.lang.Exception: Error: Unsupported expression in MLIR codegen: Promote(TropicalSemiRingType(true,false,None),Sym(v))
[error] 	at sdql.package$.raise(package.scala:4)
[error] 	at sdql.backend.MlirCodegen$.bindToName(MlirCodegen.scala:533)
[error] 	at sdql.backend.MlirCodegen$.$anonfun$bindToName$16(MlirCodegen.scala:208)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at sdql.backend.MlirCodegen$MlirBuilder.withIndent(MlirCodegen.scala:49)
[error] 	at sdql.backend.MlirCodegen$.bindToName(MlirCodegen.scala:207)
[error] 	at sdql.backend.MlirCodegen$.bindToName(MlirCodegen.scala:73)
[error] 	at sdql.backend.MlirCodegen$.run(MlirCodegen.scala:60)
[error] 	at sdql.driver.Main$.main(Main.scala:48)
[error] 	at sdql.driver.Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
[error] stack trace is suppressed; run 'last Compile / run' for the full output
[error] (Compile / run) java.lang.Exception: Error: Unsupported expression in MLIR codegen: Promote(TropicalSemiRingType(true,false,None),Sym(v))
