name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  format:
    name: "Format checks"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: scala:3.3.1 sbt

    - name: Run scalafmt
      run: sbt scalafmtCheckAll

  unit-tests:
    name: "Unit tests"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Restore Incremental Build Cache
      uses: actions/cache/restore@v4
      with:
        path: "**/target"
        key: sbt-incremental-tests-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          sbt-incremental-tests

    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: scala:3.3.1 sbt

    - name: Run tests
      run: sbt test

    - name: Update Incremental Build Cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: "**/target"
        key: sbt-incremental-tests

  filechecks:
    name: "Filechecks"

    runs-on: ubuntu-latest

    steps:

    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install lit and filecheck (python version)
      run: |
        pip install --upgrade pip
        pip install lit filecheck

    - uses: actions/checkout@v4

    - name: Cache Incremental Build
      uses: actions/cache/restore@v4
      with:
        path: "**/target"
        key: sbt-incremental-stage-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          sbt-incremental-tests

    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: scala:3.3.1 sbt
        
    - name: Package? scair-opt
      run: sbt stage

    - name: Filechecks
      run: lit tests/filecheck -v
