name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  format:
    name: "Format checks"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

    - name: SBT Cache
      uses: actions/cache@v2
      with:
        key: sbt-cache
        path: |
          ~/.iv2
          ~/.sbt
          target
          project/target
    
    - name: Run scalafmt
      run: sbt scalafmtCheckAll

  unit-tests:
    name: "Unit tests"

    runs-on: ubuntu-latest
    needs: format

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: SBT Cache
      uses: actions/cache@v2
      with:
        key: sbt-cache
        path: |
          ~/.iv2
          ~/.sbt
          target
          project/target

    - name: Run tests
      run: sbt test

  filechecks:
    name: "Filechecks"

    runs-on: ubuntu-latest
    needs: format

    steps:

    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install lit and filecheck (python version)
      run: |
        pip install --upgrade pip
        pip install lit filecheck

    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: SBT Cache
      uses: actions/cache@v2
      with:
        key: sbt-cache
        path: |
          ~/.iv2
          ~/.sbt
          target
          project/target

    - name: Package? scair-opt
      run: sbt stage

    - name: Filechecks
      run: lit tests/filecheck -v
