name: Testing

# Run on every push to main and every change on pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:

  # Build or restore MLIR once, then persist it in cache for downstream jobs.
  ensure-mlir:

    name: "Ensure MLIR availablity"

    runs-on: ubuntu-latest

    outputs:
      mlir-cache-key: ${{ steps.ensure-mlir.outputs.cache-key }}

    steps:
    - name: Checkout Scair
      uses: actions/checkout@v4
    - name: Ensure MLIR availability
      id: ensure-mlir
      uses: ./.github/actions/ensure-mlir


  # Tests and coverage
  tests:

    name: "Tests (${{ matrix.task }})"

    runs-on: ubuntu-latest
    needs:
      - ensure-mlir
    strategy:
      fail-fast: false
      matrix:
        task:
          - scoverage
          - filechecks.graal
          - filechecks.native

    steps:
    - name: Checkout Scair
      uses: actions/checkout@v4

    ##############
    # MLIR SETUP #
    ##############

    - name: Restore MLIR build cache
      uses: actions/cache/restore@v4
      with:
        key: ${{ needs.ensure-mlir.outputs.mlir-cache-key }}
        path: llvm-project/build
        fail-on-cache-miss: true
    
    ###########
    # TESTING #
    ###########

    - name: Python Setup
      uses: actions/setup-python@v7
      with:
        python-version: '3.14'

    - name: Install lit and filecheck (python version)
      run: |
        pip install --upgrade pip
        pip install "lit<23" filecheck

    # Restore Mill's incremental build cache
    - name: Restore incremental cache
      id: restore-mill-cache
      uses: actions/cache/restore@v4
      with:
        path: out
        key: mill-incremental-tests-${{ matrix.task }}${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          mill-incremental-tests-${{ matrix.task }}

    # Try to run the test, with the restored cache if any.
    # If the cache was restored, failing this falls back to the next step
    # Otherwise, it just fails the run
    - name: Run test target (incremental)
      id: cached-run
      continue-on-error: ${{ steps.restore-mill-cache.outputs.cache-matched-key != '' }}
      run: |
        export PATH=$PATH:$(pwd)/llvm-project/build/bin/
        ./mill ${{ matrix.task }}

    # This is ran only if the cache was restored and the initial attempt failed
    # Just try again from a clean slate
    - name: Run test target (clean attempt)
      if: ${{ steps.restore-mill-cache.outputs.cache-matched-key != '' && steps.cached-run.outcome == 'failure' }}
      run: |
        export PATH=$PATH:$(pwd)/llvm-project/build/bin/
        rm out -rf
        ./mill ${{ matrix.task }}

    # If tests passed, save the cache for the next run
    - name: Save incremental cache
      uses: actions/cache/save@v4
      with:
        path: out
        key: mill-incremental-tests-${{ matrix.task }}${{ github.run_id }}-${{ github.run_attempt }}

    - name: Upload coverage report to Codecov
      if: matrix.task == 'scoverage'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
