package scair.dialects.linalg

import scair.clair.*

// ██╗░░░░░ ██╗ ███╗░░██╗ ░█████╗░ ██╗░░░░░ ░██████╗░
// ██║░░░░░ ██║ ████╗░██║ ██╔══██╗ ██║░░░░░ ██╔════╝░
// ██║░░░░░ ██║ ██╔██╗██║ ███████║ ██║░░░░░ ██║░░██╗░
// ██║░░░░░ ██║ ██║╚████║ ██╔══██║ ██║░░░░░ ██║░░╚██╗
// ███████╗ ██║ ██║░╚███║ ██║░░██║ ███████╗ ╚██████╔╝
// ╚══════╝ ╚═╝ ╚═╝░░╚══╝ ╚═╝░░╚═╝ ╚══════╝ ░╚═════╝░

val LinalgDialect = summonDialect[
  (
      ElementwiseKind,
      UnaryFn,
      BinaryFn,
      TernaryFn,
      TypeFn,
      IteratorType,
  ),
  (
      Yield,
      Index,
      Softmax,
      WinogradFilterTransform,
      WinogradInputTransform,
      WinogradOutputTransform,
      Generic,
      Map,
      Reduce,
      Transpose,
      Broadcast,
      Elementwise,
      Matmul,
      Contract,
      BatchMatmul,
      BatchReduceMatmul,
      Pack,
      UnPack,
      Copy,
      Exp,
      Log,
      Abs,
      Ceil,
      Floor,
      NegF,
      Reciprocal,
      Round,
      Sqrt,
      Rsqrt,
      Square,
      Tanh,
      Erf,
      Add,
      Sub,
      Mul,
      Div,
      DivUnsigned,
      Max,
      Min,
      PowF,
      Select,
      QuantizedMatmul,
      Mmt4D,
      BatchMmt4D,
      QuantizedBatchMatmul,
      Matvec,
      Vecmat,
      BatchMatvec,
      BatchVecmat,
      Dot,
      Conv1D,
      Conv2D,
      Conv3D,
      Conv1DNwcWcf,
      Conv1DNcwFcw,
      Conv2DNhwcHwcf,
      Conv2DNhwcFhwc,
      Conv2DNhwcHwcfQ,
      Conv2DNhwcFhwcQ,
      Conv2DNchwFchwQ,
      Conv2DNchwFchw,
      Conv2DNgchwFgchw,
      Conv2DNgchwGfchw,
      Conv2DNhwgcGfhwc,
      Conv2DNhwgcGfhwcQ,
      Conv2DNgchwGfchwQ,
      Conv3DNdhwcDhwcf,
      Conv3DNdhwcDhwcfQ,
      Conv3DNcdhwFcdhw,
      DepthwiseConv1DNwcWc,
      DepthwiseConv1DNcwCw,
      DepthwiseConv1DNwcWcm,
      DepthwiseConv2DNhwcHwc,
      DepthwiseConv2DNchwChw,
      DepthwiseConv2DNhwcHwcQ,
      DepthwiseConv2DNhwcHwcm,
      DepthwiseConv2DNhwcHwcmQ,
      DepthwiseConv3DNdhwcDhwc,
      DepthwiseConv3DNcdhwCdhw,
      DepthwiseConv3DNdhwcDhwcm,
      PoolingNhwcSum,
      PoolingNchwSum,
      PoolingNhwcMax,
      PoolingNhwcMaxUnsigned,
      PoolingNchwMax,
      PoolingNhwcMin,
      PoolingNhwcMinUnsigned,
      PoolingNwcSum,
      PoolingNcwSum,
      PoolingNwcMax,
      PoolingNwcMaxUnsigned,
      PoolingNcwMax,
      PoolingNwcMin,
      PoolingNwcMinUnsigned,
      PoolingNdhwcSum,
      PoolingNdhwcMax,
      PoolingNdhwcMin,
      Fill,
      FillRng2D,
  ),
]
